### ISSUE TITLE
Push receiver for cordova

### ISSUE THREAD

**Issue by pradeepch** [LokeshPatel/Cordova-Plugin-CDVPushyMe#3]
Hi,
I am new to cordova, could you give some sample code to show received message when clicked on notification, It's not working currently, It's just opening app blank.
Thanks in advance.

**Comment by eladnava** [comment]
This issue can be fixed by:

1) Modifying [PushyMeHandlerActivity.java](https://github.com/LokeshPatel/Cordova-Plugin-CDVPushyMe/blob/e38cc799f0372bf51a24d34fea001beffef6a08d/src/android/PushyMeHandlerActivity.java) to call `forceMainActivityReload()` within the `onCreate()`
2) Modifying `forceMainActivityReload()` to call `finish()` after starting the main activity
3) Modifying `forceMainActivityReload()`'s `launchIntent` flags to `Intent.FLAG_ACTIVITY_SINGLE_TOP | Intent.FLAG_ACTIVITY_CLEAR_TOP` so that the main activity won't open more than once

I will be submitting a PR soon.
